"""Shell completion generated from the argument parser itself.

The parser is the single source of truth for what commands and flags exist, so
completion is derived from it rather than maintained beside it. A hand-kept
table would be correct exactly until the next command lands and then quietly rot,
and a stale completion is worse than none: it offers flags that no longer work.

This means reading argparse's private structures (``_actions``,
``_SubParsersAction``). That is a deliberate trade. The alternative is a second
declaration of every command, and the risk is bounded: ``probe_argparse_internals``
states exactly what is being relied on, and ``tests/test_completion.py`` calls it
so a Python upgrade that moves any of it fails loudly with a pointed message
instead of silently emitting empty scripts.

No third-party dependency is involved (rd-cli is stdlib-only), which also rules
out argcomplete.
"""

from __future__ import annotations

import argparse

SHELLS = ("bash", "zsh", "fish")


class ArgparseLayoutError(RuntimeError):
    """argparse no longer exposes what the completion walker needs."""


def probe_argparse_internals() -> None:
    """Fail loudly if the private argparse API this module walks has moved.

    Called by the test suite. Everything asserted here is exactly what `_walk`
    below depends on; if this passes, the walker can run.
    """
    p = argparse.ArgumentParser(prog="probe")
    p.add_argument("--flag")
    sub = p.add_subparsers()
    child = sub.add_parser("child")
    child.add_argument("--inner")

    if not hasattr(p, "_actions"):
        raise ArgparseLayoutError("ArgumentParser._actions is gone")
    if not hasattr(argparse, "_SubParsersAction"):
        raise ArgparseLayoutError("argparse._SubParsersAction is gone")

    subs = [a for a in p._actions if isinstance(a, argparse._SubParsersAction)]
    if not subs:
        raise ArgparseLayoutError("subparser actions are no longer in _actions")
    if not isinstance(getattr(subs[0], "choices", None), dict):
        raise ArgparseLayoutError(
            "_SubParsersAction.choices is no longer a name->parser dict"
        )
    if subs[0].choices.get("child") is not child:
        raise ArgparseLayoutError(
            "_SubParsersAction.choices no longer maps to the child parser"
        )

    flags = [a for a in p._actions if a.option_strings]
    if not any("--flag" in a.option_strings for a in flags):
        raise ArgparseLayoutError("Action.option_strings no longer lists flags")


def _walk(parser: argparse.ArgumentParser) -> dict:
    """Reduce a parser to ``{"options", "values", "subcommands"}``."""
    options: list[str] = []
    values: list[str] = []
    subcommands: dict[str, dict] = {}

    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, child in action.choices.items():
                subcommands[name] = _walk(child)
        elif action.option_strings:
            options.extend(action.option_strings)
        elif action.choices:
            # A positional with a fixed choice list, e.g. `rd completion bash`.
            # Worth completing and easy to miss: subparsers are also positionals
            # carrying `choices`, so they have to be taken off the table first or
            # every command name lands here as a value too.
            values.extend(str(c) for c in action.choices)

    return {
        "options": sorted(set(options)),
        "values": sorted(set(values)),
        "subcommands": subcommands,
    }


def describe(parser: argparse.ArgumentParser) -> dict:
    """The completion model for a parser: the shape every emitter renders."""
    return _walk(parser)


def _bash(tree: dict, prog: str) -> str:
    top = " ".join(sorted(tree["subcommands"]))
    root_opts = " ".join(tree["options"])

    # One case arm per command carrying its own flags and nested subcommands.
    arms: list[str] = []
    for name in sorted(tree["subcommands"]):
        node = tree["subcommands"][name]
        nested = " ".join(sorted(node["subcommands"]) + node["values"])
        opts = " ".join(node["options"])
        arms.append(
            f"        {name})\n"
            f"            __rd_sub='{nested}'\n"
            f"            __rd_opts='{opts}'\n"
            f"            ;;"
        )
    arm_text = "\n".join(arms)

    return f"""# {prog} completion for bash. Generated by `{prog} completion bash`.
# Install: {prog} completion bash > ~/.local/share/bash-completion/completions/{prog}
_{prog}_complete() {{
    local cur prev cmd i
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    local __rd_sub='' __rd_opts=''

    # First non-flag word after the program name is the command.
    cmd=''
    for (( i=1; i < COMP_CWORD; i++ )); do
        case "${{COMP_WORDS[i]}}" in
            -*) ;;
            *) cmd="${{COMP_WORDS[i]}}"; break ;;
        esac
    done

    if [ -z "$cmd" ]; then
        COMPREPLY=( $(compgen -W '{top} {root_opts}' -- "$cur") )
        return 0
    fi

    case "$cmd" in
{arm_text}
        *) ;;
    esac

    COMPREPLY=( $(compgen -W "$__rd_sub $__rd_opts" -- "$cur") )
    return 0
}}
complete -F _{prog}_complete {prog}
"""


def _zsh(tree: dict, prog: str) -> str:
    lines: list[str] = [
        f"#compdef {prog}",
        f"# {prog} completion for zsh. Generated by `{prog} completion zsh`.",
        f'# Install: {prog} completion zsh > "${{fpath[1]}}/_{prog}"',
        "# (then restart zsh)",
        "",
        f"_{prog}() {{",
        "    local -a cmds",
        "    cmds=(" + " ".join(f"'{n}'" for n in sorted(tree["subcommands"])) + ")",
        "    local -a opts",
        "    opts=(" + " ".join(f"'{o}'" for o in tree["options"]) + ")",
        "",
        "    if (( CURRENT == 2 )); then",
        "        _describe -t commands 'command' cmds",
        "        compadd -a opts",
        "        return",
        "    fi",
        "",
        "    case ${words[2]} in",
    ]
    for name in sorted(tree["subcommands"]):
        node = tree["subcommands"][name]
        sub = " ".join(f"'{s}'" for s in sorted(node["subcommands"]) + node["values"])
        opt = " ".join(f"'{o}'" for o in node["options"])
        lines.append(f"        {name})")
        if sub:
            lines.append(f"            local -a s; s=({sub}); compadd -a s")
        lines.append(f"            local -a o; o=({opt}); compadd -a o")
        lines.append("            ;;")
    lines += [
        "    esac",
        "}",
        "",
        f'_{prog} "$@"',
        "",
    ]
    return "\n".join(lines)


def _fish(tree: dict, prog: str) -> str:
    lines: list[str] = [
        f"# {prog} completion for fish. Generated by `{prog} completion fish`.",
        f"# Install: {prog} completion fish > ~/.config/fish/completions/{prog}.fish",
        "",
        # Without this, fish offers file paths alongside every command.
        f"complete -c {prog} -f",
        "",
    ]
    for name in sorted(tree["subcommands"]):
        lines.append(f"complete -c {prog} -n __fish_use_subcommand -a {name}")
    lines.append("")
    for name in sorted(tree["subcommands"]):
        node = tree["subcommands"][name]
        for s in sorted(node["subcommands"]) + node["values"]:
            lines.append(
                f"complete -c {prog} -n '__fish_seen_subcommand_from {name}' -a {s}"
            )
        for o in node["options"]:
            seen = f"-n '__fish_seen_subcommand_from {name}'"
            if o.startswith("--"):
                lines.append(f"complete -c {prog} {seen} -l {o[2:]}")
            elif len(o) == 2:
                lines.append(f"complete -c {prog} {seen} -s {o[1:]}")
    lines.append("")
    return "\n".join(lines)


_EMITTERS = {"bash": _bash, "zsh": _zsh, "fish": _fish}


def generate(shell: str, parser: argparse.ArgumentParser, prog: str = "rd") -> str:
    """The completion script for ``shell``, derived from ``parser``."""
    try:
        emit = _EMITTERS[shell]
    except KeyError:
        raise ValueError(
            f"unknown shell {shell!r} (expected one of: {', '.join(SHELLS)})"
        ) from None
    return emit(describe(parser), prog)
